# Generated by Django 5.0.2 on 2024-02-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggeItem',
            new_name='TaggedItem',
        ),
    ]
